name:       Build
run-name:   ${{ github.actor }} Building
on:
    push:
        branches:
            - master
jobs:
        #  windows-latest
        #  windows-2022
        #  windows-2019
        #  ubuntu-latest
        #  ubuntu-22.04
        #  ubuntu-20.04
        #  ubuntu-18.04
        #  macos-latest
        #  macos-13
        #  macos-12
        #  macos-11
    Build_on_Mac:
        runs-on:    macos-latest
        steps:
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install vera++
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install magic_enum
            - uses: actions/checkout@master
              with:
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - run: ./configure --disable-colour
            - run: make
            - run: make install
    Build_on_Linux:
        runs-on:    ubuntu-latest
        steps:
            - run: g++ --version
            - run: which g++
            - run: sudo apt-get install vera++
            - run: sudo apt-get install libboost-all-dev
            - run: git clone https://github.com/Neargye/magic_enum.git /tmp/magic_enum
            - uses: actions/checkout@master
              with:
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - run: ./configure --enable-dark-mode --with-magicenum-header-only-root=/tmp/magic_enum/include/magic_enum
            - run: |
                cat Makefile.config
                cat third/ThorsStorage/Makefile.config
                cat third/ThorsStorage/src/ThorsStorage/Makefile
            - run: make
            - run: sudo make install
    Build_on_Windows:
        runs-on:    windows-latest
        steps:
            - run:  git config --global core.autocrlf input
            - uses: actions/checkout@master
              with:
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Install MSYS2
              uses: msys2/setup-msys2@v2
              with:
                install: >-
                    autoconf
                    automake
                    make
                    git
                    gperf
                    coreutils
                    vim
                    mingw-w64-x86_64-gcc
                    mingw-w64-x86_64-gdb
                    mingw-w64-x86_64-boost
                    mingw-w64-x86_64-libyaml
                    mingw-w64-x86_64-dlfcn
            - name: GetInfo
              shell: msys2 {0}
              run: |
                uname -a
                uname -s
                uname -s | sed 's/-.*//'
            - name: Clone Magic Enum
              shell: msys2 {0}
              run:   git clone https://github.com/Neargye/magic_enum.git /tmp/magic_enum
            - uses: actions/checkout@master
            - name: Configure
              shell: msys2 {0}
              env:
                     MSYS:  winsymlinks:nativestrict
              run:  ./configure --disable-colour --disable-vera --with-magicenum-header-only-root=/tmp/magic_enum/include/magic_enum --with-yaml-root=/mingw64/ --disable-test-with-locked-file
            - name: Make
              shell: msys2 {0}
              run:   make
    Build_Header_Only_Version:
        needs:      [Build_on_Mac, Build_on_Linux, Build_on_Windows]
        runs-on:    macos-latest
        #- if:         github.ref == 'refs/heads/master'
        steps:
            - run: echo "Building Header Only"
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install vera++
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install magic_enum
            - uses: actions/checkout@master
              with:
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - run: ./configure --disable-colour
            - run: make header-only

