name:       Build
run-name:   ${{ github.actor }} Building
on:
    push:
        branches:
            - Exp4.5.01
jobs:
    Build_on_Linux:
        runs-on:    ubuntu-latest
        steps:
            - run: g++ --version
            - run: which g++
            - run: sudo apt-get install vera++
            - run: sudo apt-get install libsnappy-dev
            - run: sudo apt-get update -y && sudo apt-get install lsb-release -y && sudo apt-get clean all
            - run: git clone https://github.com/Neargye/magic_enum.git /tmp/magic_enum
            - uses: actions/checkout@master
              with:
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - run: ./configure --enable-dark-mode --with-magicenum-header-only-root=/tmp/magic_enum/include/magic_enum --disable-test-with-mongo-query --disable-Mongo-Service
            - run: |
                cat Makefile.config
                cat third/ThorsStorage/Makefile.config
                cat third/ThorsStorage/src/ThorsStorage/Makefile
            - run: make
            - run: sudo make install

